"""
Type hints for jkrc module - JAKA Robot Python SDK
"""

from typing import Any, Dict, Sequence, Tuple, Union

Joint = Tuple[float, float, float, float, float, float]
Pose = Tuple[float, float, float, float, float, float]
Rpy = Tuple[float, float, float]
FTxyz = Tuple[float, float, float, float, float, float]
CoofcAdmitConfig = Tuple[int, int, float, float, float, int]
CoofcMember = Tuple[int, int, Pose]
CoofcBodyFrame = Tuple[int, Pose]
CoofcPayloadSet = Union[Tuple[float, Rpy], Tuple[float, Rpy, FTxyz]]
CoofcPayloadGet = Tuple[float, Rpy, int, FTxyz]
CoofcForceValue = Tuple[FTxyz, Tuple[FTxyz, ...]]

# Enumerations
class CoordType:
    COORD_BASE: int
    COORD_JOINT: int
    COORD_TOOL: int

class MoveMode:
    ABS: int
    INCR: int
    CONTINUE: int
    STOP: int

# Main Robot Control Class
class RC:
    """
    Robot control class for JAKA robots.
    """
    def __init__(self, ip_addr: str) -> None: ...
    
    # Connection methods
    def login(self, use_grpc: int = 0) -> Tuple[int]: ...
    def logout(self) -> Tuple[int]: ...
    
    # Basic control methods
    def power_on(self) -> Tuple[int]: ...
    def power_off(self) -> Tuple[int]: ...
    def shut_down(self) -> Tuple[int]: ...
    def enable_robot(self) -> Tuple[int]: ...
    def disable_robot(self) -> Tuple[int]: ...
    def set_block_wait_timeout(self, seconds: float) -> Tuple[int]: ...
    def set_status_data_update_time_interval(self, millisecond: float) -> Tuple[int]: ...
    
    # Motion methods
    def jog(self, aj_num: int, move_mode: MoveMode, coord_type: CoordType, vel_cmd: float, pos_cmd: float = 0, robot_id: int = 0) -> Tuple[int]: ...
    def jog_stop(self, num: int) -> Tuple[int]: ...
    def jog_ext(self, ext_id: int, is_abs: int, vel: float, step: float) -> Tuple[int]: ...
    def enable_ext(self, ext_id: int) -> Tuple[int]: ...
    def disable_ext(self, ext_id: int) -> Tuple[int]: ...
    def get_ext_status(self, ext_id: int = -1) -> Union[Tuple[int], Tuple[int, Sequence[Dict[str, Any]]]]: ...
    def dual_arm_load_kinematics_from_controller(self) -> Tuple[int]: ...
    def get_robot_joint_position(self) -> Union[Tuple[int], Tuple[int, Joint, Joint]]: ...
    
    def joint_move(self, joint_pos: Joint, 
                   move_mode: MoveMode, is_block: bool, speed: float) -> Tuple[int]: ...
                   
    def linear_move(self, end_pos: Pose, 
                    move_mode: MoveMode, is_block: bool, speed: float) -> Tuple[int]: ...
                    
    def circular_move(self, end_pos: Pose, 
                      mid_pos: Pose, 
                      move_mode: MoveMode, is_block: bool, speed: float, accel: float, tol: float, option_cond: Any = None) -> Tuple[int]: ...
    
    # Extended motion methods
    def joint_move_extend(self, joint_pos: Joint, 
                          move_mode: MoveMode, is_block: bool, speed: float, acc: float, tol: float) -> Tuple[int]: ...
                          
    def linear_move_extend(self, end_pos: Pose, 
                           move_mode: MoveMode, is_block: bool, speed: float, accel: float, tol: float) -> Tuple[int]: ...
                           
    def linear_move_extend_ori(self, end_pos: Pose, 
                               move_mode: MoveMode, is_block: bool, speed: float, accel: float, tol: float, 
                               ori_vel: float, ori_acc: float) -> Tuple[int]: ...
    
    # Servo methods
    def servo_move_enable(
        self, 
        enable: bool, 
        is_block: bool = True, 
        robot_id: int = 0
    ) -> Tuple[int]: ...
    def is_in_servomove(self) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def servo_j(self, joint_pos: Joint, 
                move_mode: MoveMode, step_num: int = 1, do_info: Tuple[int, int, int] = ..., robot_id: int = 0) -> Tuple[int]: ...
    def servo_p(self, end_pos: Pose, 
                move_mode: MoveMode, step_num: int = 1, do_info: Tuple[int, int, int] = ..., robot_id: int = 0) -> Tuple[int]: ...
    def servo_move_ext(self, enable: bool) -> Tuple[int]: ...
    def servoj_ext(self, ext_id: int, pos: Sequence[float], step_num: int = 1) -> Tuple[int]: ...
    
    # EDG servo methods
    def edg_servo_p(self, cartesian_pose: Pose, 
                    move_mode: MoveMode, step_num: int = 1, robot_index: int = 0) -> Tuple[int]: ...
    def edg_servo_j(self, joint_pos: Joint, 
                    move_mode: MoveMode, step_num: int = 1, robot_index: int = 0) -> Tuple[int]: ...
    def edg_init(self, en: bool = True, edg_stat_ip: str = "0.0.0.0", edg_port: int = 10010, edg_mode: int = 0, prio: int = 85, cpuid: int = 3) -> Tuple[int]: ...
    def edg_init_extend(self, en: bool, edg_stat_ip: str, edg_port: int, edg_mode: int) -> Tuple[int]: ...
    def edg_recv(self) -> Tuple[int]: ...
    def edg_send(self) -> Tuple[int]: ...
    def edg_send_ext(self) -> Tuple[int]: ...
    def edg_send_with_ext(self) -> Tuple[int]: ...
    def edg_ext_servo_j(self, ext_id: int, pos: Sequence[float], move_mode: MoveMode, step_num: int = 1) -> Tuple[int]: ...
    def edg_ext_get_stat(self) -> Union[Tuple[int], Tuple[int, Sequence[Dict[str, Any]]]]: ...
    
    # Servo filter methods
    def servo_move_use_none_filter(self, robot_id: int = 0) -> Tuple[int]: ...
    def servo_move_use_joint_LPF(self, cutoffFreq: float, robot_id: int = 0) -> Tuple[int]: ...
    def servo_move_use_joint_NLF(self, max_vr: float, max_ar: float, max_jr: float, robot_id: int = 0) -> Tuple[int]: ...
    def servo_move_use_carte_NLF(self, max_vp: float, max_ap: float, max_jp: float, 
                                 max_vr: float, max_ar: float, max_jr: float, robot_id: int = 0) -> Tuple[int]: ...
    
    # Getter methods
    def get_joint_position(self) -> Union[Tuple[int], Tuple[int, Joint]]: ...
    def get_tcp_position(self) -> Union[Tuple[int], Tuple[int, Pose]]: ...
    def get_actual_joint_position(self) -> Union[Tuple[int], Tuple[int, Joint]]: ...
    def get_actual_tcp_position(self) -> Union[Tuple[int], Tuple[int, Pose]]: ...
    def set_gravity_direction(self, rpy: Rpy) -> Tuple[int]: ...
    def get_gravity_direction(self) -> Union[Tuple[int], Tuple[int, Rpy]]: ...
    def set_full_dh_flag(self, flag: int) -> Tuple[int]: ...
    
    # Error handling
    def get_last_error(self) -> Tuple[int]: ...
    def set_error_handler(self, func) -> Tuple[int]: ...
    
    # IO methods
    def get_digital_input(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def get_digital_output(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def set_digital_output(self, type: int, index: int, value: bool) -> Tuple[int]: ...
    def get_analog_input(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, float]]: ...
    def get_analog_output(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, float]]: ...
    def set_analog_output(self, type: int, index: int, value: float) -> Tuple[int]: ...
    def start_modbus_slave_node(self, submodule_id: int) -> Tuple[int]: ...
    def stop_modbus_slave_node(self, submodule_id: int) -> Tuple[int]: ...
    def enable_Hand(self, robot_id: int) -> Tuple[int]: ...
    def disable_Hand(self, robot_id: int) -> Tuple[int]: ...
    def is_Hand_Enabled(self, robot_id: int) -> Union[Tuple[int], Tuple[int, int]]: ...
    def get_Hand_State(self, robot_id: int) -> Union[Tuple[int], Tuple[int, Dict[str, Any]]]: ...
    def set_Motor_Position(self, robot_id: int, motor_id: int, pos: int) -> Tuple[int]: ...
    def set_Motor_Positions(self, robot_id: int, positions: Sequence[int]) -> Tuple[int]: ...
    def set_Raw_RxPDO(self, robot_id: int, raw_frame: bytearray) -> Tuple[int]: ...
    def get_Raw_TxPDO(self, robot_id: int) -> Union[Tuple[int], Tuple[int, bytearray]]: ...
    def enable_joint_controlloop(self, robot_id: int, joint_id: int, en: bool) -> Tuple[int]: ...
    def set_joint_controlloop(self, robot_id: int, joint_id: int, pos_kp: int, vel_kp: int, vel_ti: int) -> Tuple[int]: ...
    
    # Program methods
    def program_load(self, file: str) -> Tuple[int]: ...
    def program_run(self) -> Tuple[int]: ...
    def program_pause(self) -> Tuple[int]: ...
    def program_resume(self) -> Tuple[int]: ...
    def program_abort(self) -> Tuple[int]: ...
    
    # Tool methods
    def get_tool_id(self, robot_id: int = 0) -> Union[Tuple[int], Tuple[int, int]]: ...
    def set_tool_id(self, id: int, robot_id: int = 0) -> Tuple[int]: ...
    def set_user_frame_id(self, id: int, robot_id: int = 0) -> Tuple[int]: ...
    def get_user_frame_id(self, robot_id: int = 0) -> Union[Tuple[int], Tuple[int, int]]: ...

    # Multi-robot force-control helpers
    def robot_enable_force_control(self, robot_id: int) -> Tuple[int]: ...
    def robot_disable_force_control(self, robot_id: int) -> Tuple[int]: ...
    def robot_zero_ftsensor(self, sensor_id: int) -> Tuple[int]: ...
    def robot_zero_ftsensor_with_robot(self, robot_id: int, sensor_id: int) -> Tuple[int]: ...
    def robot_set_cst_ftframe(self, robot_id: int, ftframe: int) -> Tuple[int]: ...
    def enable_coop_force_control(self, cfcu_id: int) -> Tuple[int]: ...
    def disable_coop_force_control(self, cfcu_id: int) -> Tuple[int]: ...
    def robot_set_coofc_config(self, cfcu_id: int, config: CoofcAdmitConfig) -> Tuple[int]: ...
    def robot_get_coofc_config(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, Tuple[CoofcAdmitConfig, ...]]]: ...
    def robot_set_coofc_frame(self, cfcu_id: int, ftframe: int) -> Tuple[int]: ...
    def robot_get_coofc_frame(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, int]]: ...
    def robot_set_coofc_vel_limit(self, cfcu_id: int, vel_limit: FTxyz) -> Tuple[int]: ...
    def robot_get_coofc_vel_limit(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, FTxyz]]: ...
    def robot_set_coofc_approaching_vel_limit(self, cfcu_id: int, vel_limit: FTxyz) -> Tuple[int]: ...
    def robot_get_coofc_approaching_vel_limit(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, FTxyz]]: ...
    def robot_set_coofc_tol(self, cfcu_id: int, tol: FTxyz) -> Tuple[int]: ...
    def robot_get_coofc_tol(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, FTxyz]]: ...
    def robot_create_coofc_unit(self, cfcu_id: int, members: Sequence[CoofcMember]) -> Tuple[int]: ...
    def robot_delete_coofc_unit(self, cfcu_id: int) -> Tuple[int]: ...
    def robot_set_coofc_bodyframes(self, cfcu_id: int, bodyframes: Sequence[CoofcBodyFrame]) -> Tuple[int]: ...
    def robot_get_coofc_bodyframes(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, Tuple[CoofcBodyFrame, ...]]]: ...
    def robot_set_coofc_deadzone(self, cfcu_id: int, deadzone_percent: FTxyz) -> Tuple[int]: ...
    def robot_get_coofc_deadzone(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, FTxyz]]: ...
    def robot_set_coofc_payload(self, cfcu_id: int, payload: CoofcPayloadSet) -> Tuple[int]: ...
    def robot_get_coofc_payload(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, CoofcPayloadGet]]: ...
    def robot_get_coofc_enabled(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, int]]: ...
    def robot_get_coofc_force_value(self, cfcu_id: int) -> Union[Tuple[int], Tuple[int, CoofcForceValue]]: ...
    
    # Version methods
    def get_sdk_version(self) -> Union[Tuple[int], Tuple[int, Tuple[int, int, int, int]]]: ...
    

    # Additional exported methods.
    def add_ft_sensor(self, sensor_model: int, name: str, comm_param: str, robot_id: int) -> Tuple[Any, ...]: ...
    def add_tio_rs_signal(self, sign_info: Any) -> Tuple[Any, ...]: ...
    def call_func(self, func: Any, x: float, y: float) -> Tuple[Any, ...]: ...
    def circular_move_extend(self, end_pos: Pose, mid_pos: Pose, move_mode: MoveMode, is_block: bool, speed: float, accel: float, tol: float, option_cond: Any = None, circle_cnt: float = 0.0) -> Tuple[Any, ...]: ...
    def circular_move_extend_mode(self, end_pos: Pose, mid_pos: Pose, move_mode: MoveMode, is_block: bool, speed: float, accel: float, tol: float, option_cond: Any = None, circle_cnt: float = 0.0, circle_mode: int = 0) -> Tuple[Any, ...]: ...
    def clear_error(self) -> Tuple[Any, ...]: ...
    def close_ftp_client(self) -> Tuple[Any, ...]: ...
    def collision_recover(self) -> Tuple[Any, ...]: ...
    def create_handler(self, ip: str, use_grpc: int = 0) -> Tuple[Any, ...]: ...
    def del_ftp_file(self, remote: str, opt: int) -> Tuple[Any, ...]: ...
    def del_tio_rs_signal(self, sig_name: str) -> Tuple[Any, ...]: ...
    def destory_handler(self, handle: int) -> Tuple[Any, ...]: ...
    def disable_force_control(self) -> Tuple[Any, ...]: ...
    def download_file(self, local: str, remote: str, opt: int) -> Tuple[Any, ...]: ...
    def drag_mode_enable(self, enable: int, robot_id: int = 0) -> Tuple[int]: ...
    def dual_arm_tcp_move(self, atom0: Pose, atom1: Pose, move_mode: MoveMode, is_block: bool, vel: float, acc: float, tol: float, ext_vel: float = ..., ext_acc: float = ..., enable_head_move: int = ..., head0: float = ..., head1: float = ...) -> Tuple[Any, ...]: ...
    def edg_ext_servo_j_extend(self, ext_id: int, pos: Sequence[float], move_mode: MoveMode, step_num: int = 1) -> Tuple[Any, ...]: ...
    def edg_get_stat(self, robot_index: int = 0) -> Tuple[Any, ...]: ...
    def edg_get_stat_detail(self, robot_index: int) -> Tuple[Any, ...]: ...
    def edg_get_stat_with_ext(self) -> Tuple[Any, ...]: ...
    def edg_servo_j_with_ext(self, left_joint_pos: Union[Joint, None], right_joint_pos: Union[Joint, None], ext_pos: Union[Sequence[float], None], ext_id: int, move_mode: MoveMode, step_num: int = 1) -> Tuple[Any, ...]: ...
    def edg_stat_details(self) -> Tuple[Any, ...]: ...
    def edg_stat_free_key(self) -> Tuple[Any, ...]: ...
    def enable_admittance_ctrl(self, enable_flag: int) -> Tuple[Any, ...]: ...
    def enable_tool_drive(self, enable_flag: int) -> Tuple[Any, ...]: ...
    def generate_traj_exe_file(self, filename: str) -> Tuple[Any, ...]: ...
    def get_SDK_filepath(self) -> Tuple[Any, ...]: ...
    def get_admit_ctrl_config(self) -> Tuple[Any, ...]: ...
    def get_analog_input_with_submodule(self, type: int, index: int, submodule_id: int) -> Tuple[Any, ...]: ...
    def get_analog_output_with_submodule(self, type: int, index: int, submodule_id: int) -> Tuple[Any, ...]: ...
    def get_approach_speed_limit(self) -> Tuple[Any, ...]: ...
    def get_approaching_vel_limit(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_collision_level(self, robot_id: int = 0) -> Tuple[int, int]: ...
    def get_compliant_speed_limit(self) -> Tuple[Any, ...]: ...
    def get_compliant_type(self) -> Tuple[Any, ...]: ...
    def get_contact_force_threshold(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def get_controller_ip(self) -> Tuple[Any, ...]: ...
    def get_cst_force_ctrl_config(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_cst_force_ctrl_tol(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_current_line(self) -> Tuple[Any, ...]: ...
    def get_dh_param(self) -> Tuple[Any, ...]: ...
    def get_digital_input_with_submodule(self, type: int, index: int, submodule_id: int) -> Tuple[Any, ...]: ...
    def get_digital_output_with_submodule(self, type: int, index: int, submodule_id: int) -> Tuple[Any, ...]: ...
    def get_drag_friction_compensation_gain(self) -> Tuple[Any, ...]: ...
    def get_end_sensor_sensitivity_threshold(self) -> Tuple[Any, ...]: ...
    def get_exist_traj_file_name(self) -> Tuple[Any, ...]: ...
    def get_force_ctrl_vel_limit(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_ft_ctrl_config(self) -> Tuple[Any, ...]: ...
    def get_ft_ctrl_frame(self) -> Tuple[Any, ...]: ...
    def get_ft_ctrl_mode(self) -> Tuple[Any, ...]: ...
    def get_ft_sensor_basic_info(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_data(self, sensor_id: int, type: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_filter(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_mode(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_payload(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_ref_point(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_ft_sensor_soft_limit_rules(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_ft_tolerance(self) -> Tuple[Any, ...]: ...
    def get_ftp_dir(self, remotedir: str, type: int) -> Tuple[Any, ...]: ...
    def get_fusion_drive_sensitivity_level(self) -> Tuple[Any, ...]: ...
    def get_installation_angle(self, robot_id: int = 0) -> Tuple[Any, ...]: ...
    def get_jaka_pymoudle_version(self) -> Tuple[Any, ...]: ...
    def get_linked_ft_sensor_id(self, robot_id: int) -> Tuple[Any, ...]: ...
    def get_loaded_program(self) -> Tuple[Any, ...]: ...
    def get_loaded_program_with_size(self, size: bool) -> Tuple[Any, ...]: ...
    def get_modbus_slave_config(self, submodule_id: int) -> Tuple[Any, ...]: ...
    def get_motion_limit_waning_range(self) -> Tuple[Any, ...]: ...
    def get_motion_limit_warning_range(self) -> Tuple[Any, ...]: ...
    def get_motion_status(self) -> Tuple[Any, ...]: ...
    def get_payload(self) -> Tuple[Any, ...]: ...
    def get_program_info(self) -> Tuple[Any, ...]: ...
    def get_program_state(self) -> Tuple[Any, ...]: ...
    def get_rapidrate(self) -> Tuple[Any, ...]: ...
    def get_robot_state(self) -> Tuple[Any, ...]: ...
    def get_robot_status(self) -> Tuple[Any, ...]: ...
    def get_robot_status_simple(self) -> Tuple[Any, ...]: ...
    def get_rs485_chn_comm(self) -> Tuple[int, Dict[str, int]]: ...
    def get_rs485_chn_comm_with_robot(self, chn_id: int, robot_id: int = 0) -> Tuple[int, Dict[str, int]]: ...
    def get_rs485_chn_mode(self, chn_id: int, robot_id: int = 0) -> Tuple[int, int]: ...
    def get_rs485_signal_info(self) -> Tuple[Any, ...]: ...
    def get_tio_pin_mode(self, pin_type: int, robot_id: int = 0) -> Tuple[int, int]: ...
    def get_tio_vout_param(self, robot_id: int = 0) -> Tuple[int, int, int]: ...
    def get_tool_data(self, id: int) -> Tuple[Any, ...]: ...
    def get_tool_drive_config(self) -> Tuple[Any, ...]: ...
    def get_tool_drive_frame(self) -> Tuple[Any, ...]: ...
    def get_tool_drive_state(self) -> Tuple[Any, ...]: ...
    def get_torq_sensor_identify_staus(self) -> Tuple[Any, ...]: ...
    def get_torq_sensor_payload_identify_result(self) -> Tuple[Any, ...]: ...
    def get_torq_sensor_tool_payload(self) -> Tuple[Any, ...]: ...
    def get_torque_ref_point(self) -> Tuple[Any, ...]: ...
    def get_torque_sensor_comm(self) -> Tuple[Any, ...]: ...
    def get_torque_sensor_data(self, type: int) -> Tuple[Any, ...]: ...
    def get_torque_sensor_filter(self) -> Tuple[Any, ...]: ...
    def get_torque_sensor_mode(self) -> Tuple[Any, ...]: ...
    def get_torque_sensor_soft_limit(self) -> Tuple[Any, ...]: ...
    def get_torsenosr_brand(self) -> Tuple[Any, ...]: ...
    def get_traj_config(self) -> Tuple[Any, ...]: ...
    def get_traj_sample_status(self) -> Tuple[Any, ...]: ...
    def get_user_frame_data(self, id: int) -> Tuple[Any, ...]: ...
    def get_user_var(self) -> Tuple[Any, ...]: ...
    def init_ftp_client(self) -> Tuple[Any, ...]: ...
    def init_ftp_client_with_ssl(self, password: str) -> Tuple[Any, ...]: ...
    def is_extio_running(self, submodule_id: int = 0) -> Tuple[int, int]: ...
    def is_in_collision(self) -> Tuple[Any, ...]: ...
    def is_in_drag_mode(self) -> Tuple[Any, ...]: ...
    def is_in_estop(self) -> Tuple[Any, ...]: ...
    def is_in_pos(self) -> Tuple[Any, ...]: ...
    def is_in_servomove_with_robot(self, robot_id: int) -> Tuple[Any, ...]: ...
    def is_on_limit(self) -> Tuple[Any, ...]: ...
    def kine_forward(self, joint_pos: Joint) -> Tuple[Any, ...]: ...
    def kine_forward_extend(self, joint_pos: Joint, tool: Pose, userFrame: Pose) -> Tuple[Any, ...]: ...
    def kine_forward_with_robot(self, robot_id: int, joint_pos: Joint) -> Tuple[Any, ...]: ...
    def kine_inverse(self, ref_pos: Joint, cartesian_pose: Pose) -> Tuple[Any, ...]: ...
    def kine_inverse_extend(self, ref_pos: Joint, cartesian_pose: Pose, tool: Pose, userFrame: Pose) -> Tuple[Any, ...]: ...
    def kine_inverse_with_robot(self, robot_id: int, ref_pos: Joint, cartesian_pose: Pose) -> Tuple[Any, ...]: ...
    def motion_abort(self) -> Tuple[Any, ...]: ...
    def multi_mov_with_ext(self, info_list: Any, is_block: bool = True, planner_type: int = 0) -> Tuple[Any, ...]: ...
    def quaternion_to_rot_matrix(self, quaternion: Tuple[float, float, float, float]) -> Tuple[Any, ...]: ...
    def remove_ft_sensor(self, sensor_id: int, robot_id: int) -> Tuple[Any, ...]: ...
    def remove_traj_file(self, filename: str) -> Tuple[Any, ...]: ...
    def rename_ftp_file(self, remote: str, des: str, opt: int) -> Tuple[Any, ...]: ...
    def rename_traj_file_name(self, src: str, dest: str) -> Tuple[Any, ...]: ...
    def robot_get_cst_ftconfig(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_get_cst_ftframe(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_get_default_base(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_get_force_control_stat(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_deadzone(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_deadzone_with_robot(self, robot_id: int, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_filter(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_filter_with_robot(self, robot_id: int, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_payload(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_payload_with_robot(self, robot_id: int, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_stat(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_ftsensor_stat_with_robot(self, robot_id: int, sensor_id: int) -> Tuple[Any, ...]: ...
    def robot_get_multi_robot_dh(self) -> Tuple[Any, ...]: ...
    def robot_get_tool_offset(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_get_tool_payload(self) -> Tuple[Any, ...]: ...
    def robot_is_in_error(self) -> Tuple[Any, ...]: ...
    def robot_is_inpos(self) -> Tuple[Any, ...]: ...
    def robot_is_on_soft_limit(self, robot_id: int) -> Tuple[Any, ...]: ...
    def robot_run_multi_movj(self, robot_id: int, move_mode: Sequence[int], joint_pos: Sequence[Joint], is_block: bool, vel: Sequence[float], acc: Sequence[float], tol: Sequence[float] = ...) -> Tuple[Any, ...]: ...
    def robot_run_multi_movl(self, robot_id: int, move_mode: Sequence[int], end_pos: Sequence[Pose], is_block: bool, vel: Sequence[float], acc: Sequence[float], tol: Sequence[float] = ...) -> Tuple[Any, ...]: ...
    def robot_set_cst_ftconfig(self, robot_id: int, axis: int, enable: int, ftUser: float, ftReboundFK: float, ftConstant: float) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_deadzone(self, sensor_id: int, deadzone_percent: FTxyz) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_deadzone_with_robot(self, robot_id: int, sensor_id: int, deadzone_percent: FTxyz) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_filter(self, sensor_id: int, filter: float) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_filter_with_robot(self, robot_id: int, sensor_id: int, filter: float) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_payload(self, sensor_id: int, payload_id: int) -> Tuple[Any, ...]: ...
    def robot_set_ftsensor_payload_with_robot(self, robot_id: int, sensor_id: int, payload_id: int) -> Tuple[Any, ...]: ...
    def robot_set_tool_offset(self, robot_id: int, tool: Pose) -> Tuple[Any, ...]: ...
    def robot_set_tool_payload(self, robot_id: int, mass: float, centroid: Rpy, payload_id: int = ...) -> Tuple[Any, ...]: ...
    def rot_matrix_to_quaternion(self, rot_matrix: Tuple[Rpy, Rpy, Rpy]) -> Tuple[Any, ...]: ...
    def rot_matrix_to_rpy(self, rot_matrix: Tuple[Rpy, Rpy, Rpy]) -> Tuple[Any, ...]: ...
    def rpy_to_rot_matrix(self, rpy: Rpy) -> Tuple[Any, ...]: ...
    def send_tio_rs_command(self, chn_id: int, data: bytearray, robot_id: int = 0) -> Tuple[int]: ...
    def servo_j_extend(self, joint_pos: Joint, move_mode: MoveMode, step_num: int = 1) -> Tuple[Any, ...]: ...
    def servo_j_extend_queue(self, joint_pos: Joint, move_mode: MoveMode, step_num: int = 1, robot_id: int = 0) -> Tuple[Any, ...]: ...
    def servo_move_enable_extend(self, enable: bool, is_block: bool = True, robot_id: int = 0) -> Tuple[Any, ...]: ...
    def servo_move_use_joint_MMF(self, max_buf: int, kp: float, kv: float, ka: float, robot_id: int = 0) -> Tuple[int]: ...
    def servo_p_extend(self, cartesian_pose: Pose, move_mode: MoveMode, step_num: int = 1) -> Tuple[Any, ...]: ...
    def servo_p_extend_queue(self, cartesian_pose: Pose, move_mode: MoveMode, step_num: int = 1, robot_id: int = 0) -> Tuple[Any, ...]: ...
    def servo_speed_foresight(self, max_buf: int, kp: float, robot_id: int = 0) -> Tuple[int]: ...
    def set_SDK_filepath(self, filepath: str) -> Tuple[Any, ...]: ...
    def set_admit_ctrl_config(self, axis: int, opt: int, ftUser: float, ftConstant: float, ftNnormalTrack: int, ftReboundFK: float) -> Tuple[Any, ...]: ...
    def set_analog_output_with_submodule(self, type: int, index: int, value: float, submodule_id: int) -> Tuple[Any, ...]: ...
    def set_approach_speed_limit(self, vel: float, angularVel: float) -> Tuple[Any, ...]: ...
    def set_approaching_vel_limit(self, linear0: float, linear1: float, linear2: float, angular0: float, angular1: float, angular2: float, robot_id: int) -> Tuple[Any, ...]: ...
    def set_collision_level(self, id: int, robot_id: int = 0) -> Tuple[int]: ...
    def set_compliance_condition(self, fx: float, fy: float, fz: float, tx: float, ty: float, tz: float) -> Tuple[Any, ...]: ...
    def set_compliant_speed_limit(self, speed_limit: float, angular_speed_limit: float) -> Tuple[Any, ...]: ...
    def set_compliant_type(self, sensor_compensation: int, compliance_type: int) -> Tuple[Any, ...]: ...
    def set_contact_force_threshold(self, sensor_id: int, threshold: Sequence[float]) -> Tuple[Any, ...]: ...
    def set_cst_force_ctrl_config(self, config0: Any, config1: Any, config2: Any, config3: Any, config4: Any, config5: Any, robot_id: int) -> Tuple[Any, ...]: ...
    def set_cst_force_ctrl_tol(self, fx: float, fy: float, fz: float, tx: float, ty: float, tz: float, robot_id: int) -> Tuple[Any, ...]: ...
    def set_debug_mode(self, mode: int) -> Tuple[Any, ...]: ...
    def set_digital_output_with_submodule(self, type: int, index: int, value: int, submodule_id: int) -> Tuple[Any, ...]: ...
    def set_drag_friction_compensation_gain(self, joint: int, gain: int) -> Tuple[Any, ...]: ...
    def set_end_sensor_sensitivity_threshold(self, fx: float, fy: float, fz: float, tx: float, ty: float, tz: float) -> Tuple[Any, ...]: ...
    def set_errorcode_file_path(self, path: str) -> Tuple[Any, ...]: ...
    def set_force_ctrl_vel_limit(self, linear0: float, linear1: float, linear2: float, angular0: float, angular1: float, angular2: float, robot_id: int) -> Tuple[Any, ...]: ...
    def set_force_stop_condition(self, condition0: Any, condition1: Any, condition2: Any, condition3: Any, condition4: Any, condition5: Any) -> Tuple[Any, ...]: ...
    def set_ft_ctrl_config(self, axis: int, opt: int, ft_user: float, ft_rebound: float, ft_constant: float, ft_normal_track: int) -> Tuple[Any, ...]: ...
    def set_ft_ctrl_frame(self, ftFrame: int) -> Tuple[Any, ...]: ...
    def set_ft_ctrl_mode(self, mode: int) -> Tuple[Any, ...]: ...
    def set_ft_sensor_filter(self, sensor_id: int, filter: float) -> Tuple[Any, ...]: ...
    def set_ft_sensor_payload(self, sensor_id: int, payload_id: int) -> Tuple[Any, ...]: ...
    def set_ft_sensor_ref_point(self, x: float, y: float, z: float, robot_id: int) -> Tuple[Any, ...]: ...
    def set_ft_sensor_soft_limit_rules(self, rules: Any, robot_id: int) -> Tuple[Any, ...]: ...
    def set_ft_sensor_zero(self, sensor_id: int) -> Tuple[Any, ...]: ...
    def set_ft_tolerance(self, force: float, torque: float) -> Tuple[Any, ...]: ...
    def set_fusion_drive_sensitivity_level(self, level: int) -> Tuple[Any, ...]: ...
    def set_installation_angle(self, angleX: float, angleZ: float, robot_id: int = 0) -> Tuple[int]: ...
    def set_motion_analog_output(self, type: int, index: int, value: float, rel: int, distance: float, submodule_id: int = 0) -> Tuple[int]: ...
    def set_motion_digital_output(self, type: int, index: int, value: int, rel: int, distance: float, submodule_id: int = 0) -> Tuple[int]: ...
    def set_motion_limit_warning_range(self, warning_range: int) -> Tuple[Any, ...]: ...
    def set_motion_planner(self, type: int) -> Tuple[Any, ...]: ...
    def set_network_exception_handle_simplified(self, millisecond: float, mnt: int) -> Tuple[int]: ...
    def set_payload(self, mass: float, centroid: Rpy) -> Tuple[Any, ...]: ...
    def set_rapidrate(self, rapid_rate: float) -> Tuple[Any, ...]: ...
    def set_rs485_chn_comm(self, mod_rtu_com: Dict[str, int]) -> Tuple[int]: ...
    def set_rs485_chn_comm_with_robot(self, mod_rtu_com: Dict[str, int], robot_id: int = 0) -> Tuple[int]: ...
    def set_rs485_chn_mode(self, chn_id: int, chn_mode: int, robot_id: int = 0) -> Tuple[int]: ...
    def set_tio_pin_mode(self, pin_type: int, pin_mode: int, robot_id: int = 0) -> Tuple[int]: ...
    def set_tio_vout_param(self, vout_enable: int, vout_vol: int, robot_id: int = 0) -> Tuple[int]: ...
    def set_tool_data(self, id: int, tcp: Pose, name: str) -> Tuple[Any, ...]: ...
    def set_tool_drive_config(self, opt: int, axis: int, rebound: float, rigidity: float) -> Tuple[Any, ...]: ...
    def set_tool_drive_frame(self, ftFrame: int) -> Tuple[Any, ...]: ...
    def set_torq_sensor_tool_payload(self, mass: float, centroid: Rpy) -> Tuple[Any, ...]: ...
    def set_torque_ref_point(self, ref_point: int) -> Tuple[Any, ...]: ...
    def set_torque_sensor_comm(self, type: int, ip_addr: str, port: int) -> Tuple[Any, ...]: ...
    def set_torque_sensor_filter(self, torque_sensor_filter: float) -> Tuple[Any, ...]: ...
    def set_torque_sensor_mode(self, sensor_mode: int) -> Tuple[Any, ...]: ...
    def set_torque_sensor_soft_limit(self, fx: float, fy: float, fz: float, tx: float, ty: float, tz: float) -> Tuple[Any, ...]: ...
    def set_torsenosr_brand(self, sensor_brand: int) -> Tuple[Any, ...]: ...
    def set_traj_config(self, para: Tuple[float, float, float, float]) -> Tuple[Any, ...]: ...
    def set_user_frame_data(self, id: int, user_frame: Pose, name: str) -> Tuple[Any, ...]: ...
    def set_user_var(self, id: int, value: float, name: str) -> Tuple[Any, ...]: ...
    def set_vel_compliant_ctrl(self, vc_level: int, rate1: float, rate2: float, rate3: float, rate4: float) -> Tuple[Any, ...]: ...
    def start_torq_sensor_payload_identify(self, joint_pos: Joint) -> Tuple[Any, ...]: ...
    def tio_sensor_calib(self, type: int) -> Tuple[Any, ...]: ...
    def update_tio_rs_signal(self, sign_info: Any) -> Tuple[Any, ...]: ...
    def upload_file(self, local: str, remote: str, opt: int) -> Tuple[Any, ...]: ...
    def zero_end_sensor(self) -> Tuple[Any, ...]: ...
    # Properties
    ip_addr: str
    handle: int
    def __getattr__(self, name: str) -> Any: ...
